ARDUINO_LIBS = PJON SoftwareSerial
BOARD_TAG = nano
BOARD_SUB = atmega328
MONITOR_PORT = /dev/ttyUSB0
CXXFLAGS_STD = -std=c++11
AVR_TOOLS_DIR = /opt/arduino/hardware/tools/avr
ARDMK_DIR = /opt/arduino/Arduino-Makefile
ARDUINO_DIR = /opt/arduino
AVRDUDE = /opt/arduino/hardware/tools/avr/bin/avrdude
AVRDUDE_CONF = /opt/arduino/hardware/tools/avr/etc/avrdude.conf
include /opt/arduino/Arduino-Makefile/Arduino.mk
